name: Mwraaahh

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Random Commits (1 to 5)
        run: |
          git config --global user.name "MwrH000"
          git config --global user.email "nxy.moraa@gmail.com"
          
          COUNT=$(( ( RANDOM % 5 ) + 1 ))
          echo "Making $COUNT commits today..."

          for i in $(seq 1 $COUNT); do
            echo "Last active ($i/$COUNT): $(date -u)" >> log.txt
            git add log.txt
            git commit -m "Fixing #$i"
            sleep 2
          done

          git pull --rebase origin main
          git push